model_name_or_path: "meta-llama/Llama-2-7b-hf"
use_auth: true
output_dir: "./output/ft_test"
logging_steps: 10
save_strategy: "steps"
data_seed: 42
save_steps: 5
save_total_limit: 40
evaluation_strategy: "steps"
eval_dataset_size: 10
max_eval_samples: 10
per_device_eval_batch_size: 1
max_new_tokens: 32
dataloader_num_workers: 8
group_by_length: false
logging_strategy: "steps"
remove_unused_columns: false
do_train: true
do_eval: true
do_mmlu_eval: true
lora_r: 64
lora_alpha: 16
lora_modules: "all"
double_quant: true
quant_type: "nf4"
bf16: true
bits: 4
warmup_ratio: 0.03
lr_scheduler_type: "constant"
gradient_checkpointing: true
dataset: "oasst1"
source_max_len: 16
target_max_len: 4096
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
max_steps: 20
eval_steps: 5
learning_rate: 0.0002
adam_beta2: 0.999
max_grad_norm: 0.3
lora_dropout: 0.1
weight_decay: 0.0
seed: 0
push_to_hub: true
hub_strategy: "all_checkpoints"
hub_model_id: "HydraLM"
